name: 'EddieHubCommunity labels Action'
description: 'Import open source issue labels standards'
inputs:
  github-token:
    description: 'GitHub token for repo'
    required: true
  repository-name:
    description: 'GitHub repo name'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'get repo name'
      run: echo "::set-output name=repo::$(echo ${{ inputs.repository-name }} | tr "/" "\n" | tail -1)"
      shell: bash
    - name: 'install dependency'
      run: npm install github-label-template
      shell: bash
    - name: 'delete existing labels'
      run: npx ghlbl -o eddiejaoude -r $REPO -t ${{ inputs.github-token }} -d
      shell: bash
    - name: 'import labels from json file'
      run: npx ghlbl -o eddiejaoude -r $REPO -t ${{ inputs.github-token }} -i labels.json
      shell: bash
