name: 'EddieHubCommunity labels Action'
description: 'Import open source issue labels standards'
inputs:
  github-token:
    description: 'GitHub token for repo'
    required: true
  repository-name:
    description: 'GitHub repo name'
    required: true
outputs:
  repository:
    description: "Repo name"
    value: ${{ steps.repo-name.outputs.repo }}
runs:
  using: "composite"
  steps:
    - id: repo-name
      run: echo "::set-output name=repo::$(echo ${{ inputs.repository-name }} | tr "/" "\n" | tail -1)"
      shell: bash
    - name: 'install dependency'
      run: npm install github-label-template
      shell: bash
    - name: 'test'
      run: |
        echo "LOG START -------------"
        echo ${{ inputs.repository-name }}
        echo ${{ inputs.repository-name }} | tr "/" "\n"
        echo ${{ inputs.repository-name }} | tr "/" "\n" | tail -1
        echo $repo
        echo $repository
        echo "LOG BREAK -------------"
        npx ghlbl -o eddiejaoude -r $repository -t `${{ inputs.github-token }} | tr "/" "\n" | tail -1` -d
        echo "LOG END -------------"
      shell: bash
    - name: 'delete existing labels'
      run: npx ghlbl -o eddiejaoude -r $repository -t ${{ inputs.github-token }} -d
      shell: bash
    - name: 'import labels from json file'
      run: npx ghlbl -o eddiejaoude -r $repository -t ${{ inputs.github-token }} -i ${{ github.action_path }}/labels.json
      shell: bash
