name: 'EddieHubCommunity labels Action'
description: 'Import open source issue labels standards'
inputs:
  github-token:
    description: 'GitHub token for repo'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'install dependency'
      run: npm install github-label-template
      shell: node
    - name: 'delete existing labels'
      run: npx ghlbl -o eddiejaoude -r stargate -t ${{ inputs.github-token }} -d
      shell: node
    - name: 'import labels from json file'
      run: npx ghlbl -o eddiejaoude -r stargate -t ${{ inputs.github-token }} -i labels.json
      shell: node
