name: Import open source standard labels

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  labels:

    runs-on: ubuntu-latest

    steps:
    - uses: EddieHubCommunity/gh-action-open-source-labels@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
